In [4]:
from sklearn import preprocessing

labels = ['mario', 'rui', 'dias', 'pires']

encoder = preprocessing.LabelEncoder()
encoder.fit(labels)

for i, item in enumerate(encoder.classes_):
    print(item, '=>', i)

dias => 0
mario => 1
pires => 2
rui => 3

In [5]:
labels2 = ['mario', 'rui', 'dias', 'pires', 'rui', 'dias', 'pires', 'rui', 'dias', 'pires']
labels2_encoded = encoder.transform(labels2)

print(labels2_encoded)

[1 3 0 2 3 0 2 3 0 2]

In [6]:
import pandas as pd

from IPython.display import display

data = pd.read_csv('adult.data', header=None, index_col=False, names=['age', 'workclass', 'fnlwgt', 'education', 
                                                                      'education-num', 'marital-status', 'occupation', 
                                                                      'relationship', 'race', 'gender', 'capital-gain', 
                                                                      'capital-loss', 'hours-per-week', 'native-country', 
                                                                      'income'])

In [7]:
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']]
display(data)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>age</th>
      <th>workclass</th>
      <th>education</th>
      <th>gender</th>
      <th>hours-per-week</th>
      <th>occupation</th>
      <th>income</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>39</td>
      <td>State-gov</td>
      <td>Bachelors</td>
      <td>Male</td>
      <td>40</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>1</th>
      <td>50</td>
      <td>Self-emp-not-inc</td>
      <td>Bachelors</td>
      <td>Male</td>
      <td>13</td>
      <td>Exec-managerial</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>2</th>
      <td>38</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>40</td>
      <td>Handlers-cleaners</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>3</th>
      <td>53</td>
      <td>Private</td>
      <td>11th</td>
      <td>Male</td>
      <td>40</td>
      <td>Handlers-cleaners</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>4</th>
      <td>28</td>
      <td>Private</td>
      <td>Bachelors</td>
      <td>Female</td>
      <td>40</td>
      <td>Prof-specialty</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>5</th>
      <td>37</td>
      <td>Private</td>
      <td>Masters</td>
      <td>Female</td>
      <td>40</td>
      <td>Exec-managerial</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>6</th>
      <td>49</td>
      <td>Private</td>
      <td>9th</td>
      <td>Female</td>
      <td>16</td>
      <td>Other-service</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>7</th>
      <td>52</td>
      <td>Self-emp-not-inc</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>45</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>8</th>
      <td>31</td>
      <td>Private</td>
      <td>Masters</td>
      <td>Female</td>
      <td>50</td>
      <td>Prof-specialty</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>9</th>
      <td>42</td>
      <td>Private</td>
      <td>Bachelors</td>
      <td>Male</td>
      <td>40</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>10</th>
      <td>37</td>
      <td>Private</td>
      <td>Some-college</td>
      <td>Male</td>
      <td>80</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>11</th>
      <td>30</td>
      <td>State-gov</td>
      <td>Bachelors</td>
      <td>Male</td>
      <td>40</td>
      <td>Prof-specialty</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>12</th>
      <td>23</td>
      <td>Private</td>
      <td>Bachelors</td>
      <td>Female</td>
      <td>30</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>13</th>
      <td>32</td>
      <td>Private</td>
      <td>Assoc-acdm</td>
      <td>Male</td>
      <td>50</td>
      <td>Sales</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>14</th>
      <td>40</td>
      <td>Private</td>
      <td>Assoc-voc</td>
      <td>Male</td>
      <td>40</td>
      <td>Craft-repair</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>15</th>
      <td>34</td>
      <td>Private</td>
      <td>7th-8th</td>
      <td>Male</td>
      <td>45</td>
      <td>Transport-moving</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>16</th>
      <td>25</td>
      <td>Self-emp-not-inc</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>35</td>
      <td>Farming-fishing</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>17</th>
      <td>32</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>40</td>
      <td>Machine-op-inspct</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>18</th>
      <td>38</td>
      <td>Private</td>
      <td>11th</td>
      <td>Male</td>
      <td>50</td>
      <td>Sales</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>19</th>
      <td>43</td>
      <td>Self-emp-not-inc</td>
      <td>Masters</td>
      <td>Female</td>
      <td>45</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>20</th>
      <td>40</td>
      <td>Private</td>
      <td>Doctorate</td>
      <td>Male</td>
      <td>60</td>
      <td>Prof-specialty</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>21</th>
      <td>54</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Female</td>
      <td>20</td>
      <td>Other-service</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>22</th>
      <td>35</td>
      <td>Federal-gov</td>
      <td>9th</td>
      <td>Male</td>
      <td>40</td>
      <td>Farming-fishing</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>23</th>
      <td>43</td>
      <td>Private</td>
      <td>11th</td>
      <td>Male</td>
      <td>40</td>
      <td>Transport-moving</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>24</th>
      <td>59</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Female</td>
      <td>40</td>
      <td>Tech-support</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>25</th>
      <td>56</td>
      <td>Local-gov</td>
      <td>Bachelors</td>
      <td>Male</td>
      <td>40</td>
      <td>Tech-support</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>26</th>
      <td>19</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>40</td>
      <td>Craft-repair</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>27</th>
      <td>54</td>
      <td>?</td>
      <td>Some-college</td>
      <td>Male</td>
      <td>60</td>
      <td>?</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>28</th>
      <td>39</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>80</td>
      <td>Exec-managerial</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>29</th>
      <td>49</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>40</td>
      <td>Craft-repair</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>32531</th>
      <td>30</td>
      <td>?</td>
      <td>Bachelors</td>
      <td>Female</td>
      <td>99</td>
      <td>?</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32532</th>
      <td>34</td>
      <td>Private</td>
      <td>Doctorate</td>
      <td>Male</td>
      <td>60</td>
      <td>Prof-specialty</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32533</th>
      <td>54</td>
      <td>Private</td>
      <td>Bachelors</td>
      <td>Male</td>
      <td>50</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32534</th>
      <td>37</td>
      <td>Private</td>
      <td>Some-college</td>
      <td>Female</td>
      <td>39</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32535</th>
      <td>22</td>
      <td>Private</td>
      <td>12th</td>
      <td>Male</td>
      <td>35</td>
      <td>Protective-serv</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32536</th>
      <td>34</td>
      <td>Private</td>
      <td>Bachelors</td>
      <td>Female</td>
      <td>55</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32537</th>
      <td>30</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>46</td>
      <td>Craft-repair</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32538</th>
      <td>38</td>
      <td>Private</td>
      <td>Bachelors</td>
      <td>Female</td>
      <td>45</td>
      <td>Prof-specialty</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32539</th>
      <td>71</td>
      <td>?</td>
      <td>Doctorate</td>
      <td>Male</td>
      <td>10</td>
      <td>?</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32540</th>
      <td>45</td>
      <td>State-gov</td>
      <td>HS-grad</td>
      <td>Female</td>
      <td>40</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32541</th>
      <td>41</td>
      <td>?</td>
      <td>HS-grad</td>
      <td>Female</td>
      <td>32</td>
      <td>?</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32542</th>
      <td>72</td>
      <td>?</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>25</td>
      <td>?</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32543</th>
      <td>45</td>
      <td>Local-gov</td>
      <td>Assoc-acdm</td>
      <td>Female</td>
      <td>48</td>
      <td>Prof-specialty</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32544</th>
      <td>31</td>
      <td>Private</td>
      <td>Masters</td>
      <td>Female</td>
      <td>30</td>
      <td>Other-service</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32545</th>
      <td>39</td>
      <td>Local-gov</td>
      <td>Assoc-acdm</td>
      <td>Female</td>
      <td>20</td>
      <td>Adm-clerical</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32546</th>
      <td>37</td>
      <td>Private</td>
      <td>Assoc-acdm</td>
      <td>Female</td>
      <td>40</td>
      <td>Tech-support</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32547</th>
      <td>43</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>40</td>
      <td>Machine-op-inspct</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32548</th>
      <td>65</td>
      <td>Self-emp-not-inc</td>
      <td>Prof-school</td>
      <td>Male</td>
      <td>60</td>
      <td>Prof-specialty</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32549</th>
      <td>43</td>
      <td>State-gov</td>
      <td>Some-college</td>
      <td>Female</td>
      <td>40</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32550</th>
      <td>43</td>
      <td>Self-emp-not-inc</td>
      <td>Some-college</td>
      <td>Male</td>
      <td>50</td>
      <td>Craft-repair</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32551</th>
      <td>32</td>
      <td>Private</td>
      <td>10th</td>
      <td>Male</td>
      <td>40</td>
      <td>Handlers-cleaners</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32552</th>
      <td>43</td>
      <td>Private</td>
      <td>Assoc-voc</td>
      <td>Male</td>
      <td>45</td>
      <td>Sales</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32553</th>
      <td>32</td>
      <td>Private</td>
      <td>Masters</td>
      <td>Male</td>
      <td>11</td>
      <td>Tech-support</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32554</th>
      <td>53</td>
      <td>Private</td>
      <td>Masters</td>
      <td>Male</td>
      <td>40</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32555</th>
      <td>22</td>
      <td>Private</td>
      <td>Some-college</td>
      <td>Male</td>
      <td>40</td>
      <td>Protective-serv</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32556</th>
      <td>27</td>
      <td>Private</td>
      <td>Assoc-acdm</td>
      <td>Female</td>
      <td>38</td>
      <td>Tech-support</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32557</th>
      <td>40</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>40</td>
      <td>Machine-op-inspct</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32558</th>
      <td>58</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Female</td>
      <td>40</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32559</th>
      <td>22</td>
      <td>Private</td>
      <td>HS-grad</td>
      <td>Male</td>
      <td>20</td>
      <td>Adm-clerical</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32560</th>
      <td>52</td>
      <td>Self-emp-inc</td>
      <td>HS-grad</td>
      <td>Female</td>
      <td>40</td>
      <td>Exec-managerial</td>
      <td>&gt;50K</td>
    </tr>
  </tbody>
</table>
<p>32561 rows × 7 columns</p>
</div>

In [21]:
print(list(data.columns))
data_dummies = pd.get_dummies(data)

print(list(data_dummies.columns))

['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']
['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-serv', 'occupation_ Sales', 'occupation_ Tech-support', 'occupation_ Transport-moving', 'income_ <=50K', 'income_ >50K']

In [23]:
features = data_dummies.loc[data_dummies.index[:], 'age':'occupation_ Transport-moving']

In [27]:
X = features.values
y = data_dummies['income_ >50K'].values

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
logreg = LogisticRegression()

logreg.fit(X_train, y_train)

print(logreg.score(X_test, y_test))

0.8085001842525489